# SPDX-FileCopyrightText: 2025 hexaTune LLC
# SPDX-License-Identifier: MIT

welcome:
  newPRWelcomeComment: >
    ðŸ‘‹ **Welcome to hexaMobileShare!**  
    Thank you for your first pull request ðŸŽ‰  
    A maintainer will review it soon.  
    In the meantime, please make sure your PR follows our [contribution guidelines](https://github.com/hTuneSys/hexaMobileShare/blob/main/.github/CONTRIBUTING.md).  
    Happy hacking! ðŸš€

  newIssueWelcomeComment: >
    ðŸ‘‹ Welcome!  
    Thanks for submitting your first issue.  
    A maintainer will look into it shortly.  
    While you wait, you might want to check our [FAQ](https://github.com/hTuneSys/hexaMobileShare/blob/main/docs/FAQ.md) or [README](https://github.com/hTuneSys/hexaMobileShare#readme) for helpful info.
